### ISSUE TITLE
Categorical Histogram can't be created when operating on a table with ranges

### ISSUE THREAD

**Issue by alexsb** [phovea/phovea_core#93]
This is a problem in Lineage, but I think it's related to phovea core.

This line fails: 
https://github.com/Caleydo/lineage/commit/ee15bb3d50b018b516190b86996b8223f1f72db3#diff-98337d50647f83d43632199c96d1cd09R257

With this error:

```
Uncaught (in promise) RangeError: end of iterator
    at Iterator.next (http://localhost:8080/app.js:29250:19)
    at http://localhost:8080/app.js:6602:34
    at Array.forEach (native)
    at CatHistogram.AHistogram.pushAll (http://localhost:8080/app.js:6601:17)
    at categoricalHist (http://localhost:8080/app.js:6517:7)
    at TableVector.<anonymous> (http://localhost:8080/app.js:19677:140)
    at step (http://localhost:8080/app.js:137:23)
    at Object.next (http://localhost:8080/app.js:118:53)
    at fulfilled (http://localhost:8080/app.js:108:58)
```

### Steps to reproduce

1.  Checkout the above referenced state, fails on console. 

Note that this operation seems to work fine on a table that is in no way a view.

**Comment by alexsb** [comment]
While this is consistently reproducible in the referenced application, I can't reproduce it in the phovea_demo repository no matter how much I slice. 

It's also not related to missing values.

**Comment by sgratzl** [comment]
next time please also link to the data that you are using. 

the issue was that the data definition is `size: [ <number of rows>, <number of columns> ]`, in your case you have 193 data items but the system think there are just 13 according to the definition

see https://github.com/Caleydo/lineage_server/commit/64f0a9a793eff3fa59c1984b9df8ae808fc9314d
